######################################################################
# Automatically generated by qmake (3.0) Mon Sep 30 18:50:14 2013
######################################################################

QT += core gui opengl
QMAKE_CXXFLAGS += -std=c++11
TEMPLATE = app
TARGET = kbplot
INCLUDEPATH += .

# Input
HEADERS += glwidget.h kbplot.h
SOURCES += glwidget.cpp main.cpp kbplot.cpp
