######################################################################
# Automatically generated by qmake (3.0) Mon Sep 30 18:50:14 2013
######################################################################

QT += core gui opengl
QMAKE_CXXFLAGS += -w -DDEBUG
TEMPLATE = app
TARGET = kbplot
INCLUDEPATH += .

# Input
HEADERS += glwidget.h kbplot.h event.h graphical_object.h
SOURCES += glwidget.cpp main.cpp kbplot.cpp graphical_object.cpp
